# local_repository(
#     name = "rules_mobile_assets",
#     path = "../",
# )

# load("@rules_mobile_assets//mobile_assets:repositories.bzl", "rules_mobile_assets_dependencies")
#
# rules_mobile_assets_dependencies()

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# http_archive(
#     name = "rules_mobile_assets",
#     sha256 = "23301194bc480d527fbb4ad777e00c5101527aab740800e92f561f4d4445b001",
#     strip_prefix = "rules_mobile_assets-0.0.1",
#     url = "https://github.com/ChristianBelloni/rules_mobile_assets/releases/download/0.0.1/rules_mobile_assets-0.0.1.tar.gz",
# )

local_repository(
    name = "rules_mobile_assets",
    path = "..",
)

load("@rules_mobile_assets//mobile_assets:repositories.bzl", "rules_mobile_assets_dependencies")

rules_mobile_assets_dependencies()

load("@rules_mobile_assets//mobile_assets:setup.bzl", "rules_mobile_assets_setup")

rules_mobile_assets_setup()
