name: Release
on:
  push:
    tags:
      - "*.*.*"
permissions:
  contents: write
jobs:
  release:
    uses: bazel-contrib/.github/.github/workflows/release_ruleset.yaml@v6
    with:
      release_files: rules_mobile_assets-*.tar.gz
      bazel_test_command: echo "testing not supported at the moment"
